### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by JouleCai** [space-physics/igrf#13]
I got the following message when I call the igrf module. It looks like that the required files cannot be found and the search path is redirected to my home folder. Could you please help to check the problem?

>>> import igrf
>>> mag = igrf.igrf('2010-07-12', glat=65, glon=-148, alt_km=100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lei/igrf/src/igrf/base.py", line 134, in igrf
    ret = subprocess.run(cmd, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/home/lei/.conda/envs/eiscat_cdt/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/lei/.conda/envs/eiscat_cdt/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/lei/.conda/envs/eiscat_cdt/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/lei/igrf/src/igrf/igrf13_driver'

**Comment by JWiker** [comment]
I'm also getting this - @scivision would you be able to help us find the issue?

**Comment by umbertowski** [comment]
I'm also got this issue, I've tried to make some changes in base.py but it still not working

> Traceback (most recent call last):
  File "/Users/umbertomoffa/PycharmProjects/pythonProject7/main.py", line 68, in <module>
    print_hi ('PyCharm')
  File "/Users/umbertomoffa/PycharmProjects/pythonProject7/main.py", line 51, in print_hi
    mag = igrf ('2010-07-12', glat = 65, glon = -148, alt_km = 100)
  File "/Users/umbertomoffa/opt/anaconda3/envs/pythonProject7/lib/python3.10/site-packages/igrf/base.py", line 137, in igrf
    ret = subprocess.run(cmd, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/Users/umbertomoffa/opt/anaconda3/envs/pythonProject7/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/umbertomoffa/opt/anaconda3/envs/pythonProject7/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/umbertomoffa/opt/anaconda3/envs/pythonProject7/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
**FileNotFoundError: [Errno 2] No such file or directory: '/Users/umbertomoffa/opt/anaconda3/envs/pythonProject7/lib/python3.10/site-packages/igrf/igrf13_driver'**

Have you guys find a solution for this problem? @JWiker @JouleCai 

Can you help us? @scivision

**Comment by JWiker** [comment]
> Have you guys find a solution for this problem? @JWiker @JouleCai

Unfortunately not, still seeing the issue. Hopefully @scivision can help?

**Comment by hisahon** [comment]
I think i found the solution, to me the problem was solved building compiler manually. (Just once.)
![image](https://user-images.githubusercontent.com/106283361/178581982-fe85567c-9299-4632-ba38-05bc2912b81b.png)
![image](https://user-images.githubusercontent.com/106283361/178582123-1d59e076-96b7-47a5-afbc-a22bdd120fb7.png)
